// app/layout.tsx
import { Inter } from "next/font/google";
import "./globals.scss";
import StoreProvider from "./StoreProvider";
import { makeStore } from "../lib/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
