// app/layout.tsx
import React from 'react';
import { Inter } from "next/font/google";
import "./globals.scss"; // Import global SCSS styles
import StoreProvider from "./StoreProvider";
import { AntdRegistry } from '@ant-design/nextjs-registry'; // Import Ant Design registry

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <StoreProvider>
            {children}
          </StoreProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
